### ISSUE TITLE
will you support opengl

### ISSUE THREAD

**Issue by lty123456** [cloudwu/efkbgfx#37]
I add it to my project,work perfact on vulkan/dx11,but on opengl, it can not be compile when loading stage,then i try to fix sc files:
1: instead VS_Output Output = (VS_Output)0; To
    #if BGFX_SHADER_LANGUAGE_HLSL
    VS_Output Output = (VS_Output)0;
    #else
    VS_Output Output;
    #endif
2: instead struct BgfxSampler2D To sampler2D,
  After that shader can be load(compile),but a lot of WARN i get like:"WARN User defined uniform 's_blendUVDistortionTex' is not found, it won't be set.",i read the code of unifrom part,i never see create uniform like efkbgfx style in other bgfx project,why not use bgfx::createUniform?,anyway,will you support opengl?

**Comment by cloudwu** [comment]
Supporting opengl is not simple , a lot of work need to do. The official effekseer use [LLGI](https://github.com/altseed/LLGI) to support opengl , but bgfx has its own shader format. We have to maintain opengl version manually. We can't afford it right now. But I think you can try it by yourself.

For the question 2, `VS_Output Ouput;` is not the equivalent to `VS_Output Output = (VS_Output)0;`, you should clear the `Output` rather than ignore it. If you ignore the `Output`, some uniform like 's_blendUVDistortionTex' would be optimized by the `shaderc` of bgfx.

**Comment by lty123456** [comment]
I got it,i have to do my work everyday,i would try your suggest in future days,wish no other issues found.

**Comment by lty123456** [comment]
I found use vulkan works fine too,it may not optimized by the shaderc,i debug the source, i found the diffrence between vulkan and opengl is that opengl can't get unifrom size in a shader,because in function: bgfx::createShader(const Memory* _mem)//line 4071 in bgfx_p.h
this function read *.bin file data and store uniform info,but in opengl it readed count always be zero:

> 			uint16_t count;//line 4142
> 			bx::read(&reader, count, &err);

Than i check the *(same).bin file between glsl and spiv compiled output,glsl bin files acturely lack of these uniform statistics infomation,
Do you think is it an issue that bgfx::getShaderUniforms always return 0 in glsl?

**Comment by lty123456** [comment]
i assume getShaderUniforms get 0 will cause efkbgfx can not set unifroms correctly,because i know 0 about efkbgfx uniform style

**Comment by cloudwu** [comment]
I don't think shaderc doesn't write the count of uniform, check
https://github.com/bkaradzic/bgfx/blob/master/tools/shaderc/shaderc_glsl.cpp#L353

**Comment by lty123456** [comment]
i debug the shaderc,

> 							if ( (profile->lang == ShadingLang::GLSL && glsl_profile > 400)
> 							||   (profile->lang == ShadingLang::ESSL && glsl_profile > 300) )
> 							{
> 								code += preprocessor.m_preprocessed;
> 
> 								bx::write(_shaderWriter, uint16_t(0), &err);
> 
> 								uint32_t shaderSize = (uint32_t)code.size();
> 								bx::write(_shaderWriter, shaderSize, &err);
> 								bx::write(_shaderWriter, code.c_str(), shaderSize, &err);
> 								bx::write(_shaderWriter, uint8_t(0), &err);
> 
> 								compiled = true;
> 							}
> 							else
> 							{
> 								code += _comment;
> 								code += preprocessor.m_preprocessed;
> 
> 								if (profile->lang == ShadingLang::ESSL)
> 								{
> 									glsl_profile |= 0x80000000;
> 								}
> 
> 								compiled = compileGLSLShader(_options, glsl_profile, code, _shaderWriter, _messageWriter);
> 							}
above code in shaderc.cpp from line 2542,
my cmake function compile sc files is copy from bgfx example function add_example_shader:

> _bgfx_shaderc_parse(GLSL ${COMMON} LINUX PROFILE 420 OUTPUT ${GLSL_OUTPUT})
So 420 will not run into compileGLSLShader cause bin files without uniform info,
I change 420 to 150,and efkbgfx example in opengl is workable now.
by the way,i found if i change 420 to 400 shaderc will report error,but 150 410 420 430 are ok.

**Comment by lty123456** [comment]
do you need a pr

**Comment by lty123456** [comment]
i make a mistake: bgfx cmake function to compile shader is 140,default is ok
